version: '3.8'
services:
  pizzashop:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pizzashop
      - SERVER_PORT=8080
      - LOGGING_LEVEL_COM_CLOUDGOV_PIZZASHOP=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=INFO
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pizzashop

volumes:
  mongodb_data: