version: '3.8'
services:
  pizzashop:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SERVER_PORT=${SERVER_PORT:-8080}  
      - LOGGING_LEVEL_COM_CLOUDGOV_PIZZASHOP=${LOGGING_LEVEL_COM_CLOUDGOV_PIZZASHOP}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
      - LOGGING_FILE_NAME=${LOGGING_FILE_NAME}
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - pizza-net

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pizzashop
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pizza-net

networks:
  pizza-net:
    driver: bridge

volumes:
  mongodb_data: